## Model Training

In [2]:
import pandas as pd

In [4]:
df=pd.read_csv('data/gemstone.csv')
df.head()

   id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [6]:
df=df.drop(labels=['id'],axis=1)
df

        carat        cut color clarity  depth  table     x     y     z  price
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453
...       ...        ...   ...     ...    ...    ...   ...   ...   ...    ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67   1130
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47   2874
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62   3036
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81    681
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48   2258

[193573 rows x 10 columns]

In [9]:
x=df.drop(labels=['price'],axis=1)
y=df['price']

In [12]:
categorical_cols=x.select_dtypes(include='object').columns
numerical_cols=x.select_dtypes(exclude='object').columns

In [21]:
from sklearn.impute import SimpleImputer ##handling missing values
from sklearn.preprocessing import StandardScaler ## Handling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder ## Ordinal Encoding
## import piplines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [57]:
cut_cat=['Fair','Good','Very Good','Premium','Ideal']
clarity_cat=['I1','SI2','SI1','VS2','VS1','VVS2','VVS1','IF']
color_cat=['D','E','F','G','H','I','J']

In [38]:
numerical_cols

Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [58]:
#numerical Pipeline
num_pipeline=Pipeline(
    steps=[
      ('imputer',SimpleImputer(strategy='median')),
      ('scaler',StandardScaler())
           
      
      ]
)
cat_pipeline=Pipeline(
    steps=[
('imputer',SimpleImputer(strategy='most_frequent')),
('ordinal_encoder',OrdinalEncoder(categories=[cut_cat,color_cat,clarity_cat])),
('scaler',StandardScaler())
    ]
)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)

])

In [59]:
#Train Test Split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=30)

In [35]:
x_train

        carat      cut color clarity  depth  table     x     y     z
168192   0.34    Ideal     I    VVS2   60.9   57.0  4.56  4.53  2.76
35202    0.90     Good     E     SI1   63.8   57.0  6.07  6.03  3.87
41091    1.02  Premium     G     VS1   62.7   58.0  6.35  6.39  4.00
31239    0.32  Premium     G     VS2   62.1   59.0  4.37  4.35  2.71
45722    0.35    Ideal     J    VVS2   61.1   56.0  4.53  4.57  2.78
...       ...      ...   ...     ...    ...    ...   ...   ...   ...
66455    0.31    Ideal     E     SI1   61.8   56.0  4.31  4.35  2.68
46220    1.25    Ideal     G     SI2   62.0   56.0  6.88  6.95  4.28
98804    1.00     Good     G     SI1   63.5   56.0  6.29  6.37  4.02
48045    1.10    Ideal     G     VS1   59.9   60.0  6.68  6.77  4.01
169765   0.91    Ideal     G     SI1   62.7   57.0  6.14  6.18  3.86

[135501 rows x 9 columns]

In [60]:
preprocessor.fit_transform(x_train)

array([[-0.97543926, -0.84960654, -0.12153081, ...,  0.87407553,
         1.52872212,  1.35273128],
       [ 0.2351953 ,  1.83363716, -0.12153081, ..., -2.14455824,
        -0.93507064, -0.64678628],
       [ 0.49461699,  0.81585507,  0.39980029, ..., -0.13213573,
         0.29682574,  0.68622543],
       ...,
       [ 0.45138004,  1.55606023, -0.6428619 , ..., -2.14455824,
         0.29682574, -0.64678628],
       [ 0.66756478, -1.77486298,  1.44246248, ...,  0.87407553,
         0.29682574,  0.68622543],
       [ 0.25681377,  0.81585507, -0.12153081, ...,  0.87407553,
         0.29682574, -0.64678628]])